# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d77b2929790b674a575e3e9a5cb51fddb8612108401b657c1a85ec73987e0d857a49509e8937754d6d9e15c6a65e45bcd3deb73c9816099d42eeeaaf45d779b2

test:
  secret_key_base: 9f2cf66b3e85a0e948030152fabf1b9a7d7776d5a4f615a174617e6b98557e4d6c00225dd546e5f5f3fd76a1f30ac285ad7ab37f0aeab515d288ee3634fa3ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
